name: Compilar EXE

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar ejecutable Single-File
      run: dotnet publish GeneradorXML.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:EnableCompressionInSingleFile=true -o ./dist

    - name: Subir ejecutable
      uses: actions/upload-artifact@v4
      with:
        name: GeneradorXML_EXE
        path: ./dist/*.exe
