name: Compilar EXE

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Compilar ejecutable autodetenido (.exe único)
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:EnableCompressionInSingleFile=true -o ./dist

    - name: Subir EXE
      uses: actions/upload-artifact@v3
      with:
        name: GeneradorXML_EXE
        path: ./dist/*.exe
